# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNAdsb40tIS3mP0Kr01QGqMoyh1Namvu
"""

import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.cm as cm

st.set_page_config(layout="wide")

# Load data
@st.cache_data
def load_data():
    return pd.read_csv("merged_clean.csv")

df = load_data()

# Clean
df = df.dropna(subset=["PhecodeCategory", "PhecodeString", "ICD", "dx name"])

# Filters
st.title("Juvenile Fibromyalgia Drilldown Explorer")

col1, col2 = st.columns(2)
category = col1.selectbox("Select Category", ["All"] + sorted(df["PhecodeCategory"].unique()))
if category != "All":
    df = df[df["PhecodeCategory"] == category]

phecode = col2.selectbox("Select Phecode", ["All"] + sorted(df["PhecodeString"].unique()))
if phecode != "All":
    df = df[df["PhecodeString"] == phecode]

# Determine level
if category == "All":
    level = "PhecodeCategory"
elif phecode == "All":
    level = "PhecodeString"
else:
    level = "ICD + dx name"
    df["ICD + dx name"] = df["ICD"] + " — " + df["dx name"]

# Top N slider
top_n = st.slider("Select Top N Results", 5, 50, 20)

# Display chart
st.markdown(f"### Frequency by **{level}**")
data = df[level].value_counts().head(top_n)

if data.empty:
    st.warning("No data available for this selection.")
else:
    st.write(f"Total count: **{int(data.sum())}**")

    fig, ax = plt.subplots(figsize=(10, 5))
    colors = cm.viridis(data.values / max(data.values))
    bars = ax.barh(data.index, data.values, color=colors)
    ax.set_xlabel("Frequency")
    ax.set_ylabel(level)
    ax.set_title(f"Top {top_n} Frequencies")

    for bar in bars:
        width = bar.get_width()
        ax.text(width + 1, bar.get_y() + bar.get_height() / 2, str(int(width)), va='center')

    ax.invert_yaxis()
    st.pyplot(fig)